// src/screens/OrderReportScreen.tsx
// Dynamic Schedule-Based Order Report — "2AM - Daily Replenishment Guide"
import React, { useMemo, useState } from 'react';
import {
  View, Text, ScrollView, StyleSheet, TouchableOpacity, Platform, TextInput,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useStore } from '../store/useStore';
import { WebScrollView } from '../components/WebScrollView';
import { Colors, useColors, Spacing, Radius, FontSize } from '../theme/colors';
import { calculateDynamicOrder, getDaysToCover, DynamicOrderLine } from '../lib/orderCalculator';
import { Vendor } from '../types';

// ── Day helpers ───────────────────────────────────────────────
const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

function formatDate(d: Date) {
  return d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' });
}

function toInputDate(d: Date) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function parseInputDate(s: string): Date | null {
  const parts = s.split('-');
  if (parts.length !== 3) return null;
  const d = new Date(parseInt(parts[0]), parseInt(parts[1]) - 1, parseInt(parts[2]));
  return isNaN(d.getTime()) ? null : d;
}

// ── CSV Export ────────────────────────────────────────────────
function exportToCSV(data: DynamicOrderLine[], vendorName: string, dateStr: string) {
  const headers = ['Item Name', 'Category', 'Unit', 'Daily Usage', 'Days to Cover', 'Safety Stock', 'Target Par', 'EOD Remaining', 'Order Qty', 'Cost/Unit', 'Est. Cost'];
  const rows = data.map((d) => [
    d.itemName, d.category, d.unit,
    d.dailyUsage, d.daysToCover, d.safetyStock, d.dynamicPar,
    d.eodRemaining, d.orderQuantity,
    d.costPerUnit.toFixed(2), d.estimatedCost.toFixed(2),
  ]);

  const csv = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `2AM_Order_${vendorName.replace(/\s/g, '_')}_${dateStr}.csv`;
  link.click();
  URL.revokeObjectURL(url);
}

// ── PDF Export ────────────────────────────────────────────────
async function exportToPDF(data: DynamicOrderLine[], vendorName: string, storeName: string, orderDate: Date, daysToCover: number) {
  const { default: jsPDF } = await import('jspdf');
  await import('jspdf-autotable');

  const dateStr = formatDate(orderDate);
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('2AM', 14, 20);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Daily Replenishment Guide', 14, 28);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Store: ${storeName}  |  Vendor: ${vendorName}  |  Order Date: ${dateStr}`, 14, 35);
  doc.text(`${data.length} items  |  ${daysToCover} days coverage  |  Est. total: $${data.reduce((s, d) => s + d.estimatedCost, 0).toFixed(2)}`, 14, 41);

  (doc as any).autoTable({
    startY: 48,
    head: [['Item', 'Category', 'Unit', 'Daily Use', 'Days', 'Target Par', 'EOD Rem.', 'Order Qty', 'Est. Cost']],
    body: data.map((d) => [
      d.itemName, d.category, d.unit,
      d.dailyUsage, d.daysToCover, d.dynamicPar,
      d.eodRemaining, d.orderQuantity,
      `$${d.estimatedCost.toFixed(2)}`,
    ]),
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [26, 26, 24], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 245, 243] },
    columnStyles: {
      3: { halign: 'center' },
      4: { halign: 'center' },
      5: { halign: 'center' },
      6: { halign: 'center' },
      7: { halign: 'center', fontStyle: 'bold', textColor: [121, 31, 31] },
      8: { halign: 'right' },
    },
  });

  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by 2AM Inventory Management System', 14, pageHeight - 10);

  const isoDate = toInputDate(orderDate);
  doc.save(`2AM_Order_${vendorName.replace(/\s/g, '_')}_${isoDate}.pdf`);
}

// ── Main Screen ──────────────────────────────────────────────
export default function OrderReportScreen() {
  const { inventory, vendors, currentStore } = useStore();
  const [selectedVendorId, setSelectedVendorId] = useState<string>('all');
  const [dateInput, setDateInput] = useState(toInputDate(new Date()));
  const C = useColors();

  const orderDate = useMemo(() => parseInputDate(dateInput) || new Date(), [dateInput]);

  const storeInventory = useMemo(
    () => inventory.filter((i) => i.storeId === currentStore.id),
    [inventory, currentStore.id]
  );

  // Vendors that have items in this store
  const activeVendors = useMemo(() => {
    const vendorIds = new Set(storeInventory.map((i) => i.vendorId));
    return vendors.filter((v) => vendorIds.has(v.id));
  }, [storeInventory, vendors]);

  // Calculate order lines
  const orderLines = useMemo(() => {
    if (selectedVendorId === 'all') {
      return activeVendors
        .flatMap((v) => calculateDynamicOrder(storeInventory, v, orderDate))
        .sort((a, b) => a.vendor.localeCompare(b.vendor) || a.itemName.localeCompare(b.itemName));
    }
    const vendor = vendors.find((v) => v.id === selectedVendorId);
    if (!vendor) return [];
    return calculateDynamicOrder(storeInventory, vendor, orderDate);
  }, [storeInventory, activeVendors, vendors, selectedVendorId, orderDate]);

  const totalCost = useMemo(
    () => orderLines.reduce((sum, l) => sum + l.estimatedCost, 0),
    [orderLines]
  );

  // Group by vendor for display
  const vendorGroups = useMemo(() => {
    const groups: Record<string, { vendor: Vendor; lines: DynamicOrderLine[]; daysToCover: number }> = {};
    orderLines.forEach((line) => {
      if (!groups[line.vendor]) {
        const v = vendors.find((ven) => ven.name === line.vendor)!;
        groups[line.vendor] = { vendor: v, lines: [], daysToCover: line.daysToCover };
      }
      groups[line.vendor].lines.push(line);
    });
    return groups;
  }, [orderLines, vendors]);

  const isWeb = Platform.OS === 'web';

  const handleCSV = () => {
    if (!isWeb) return;
    const vendorLabel = selectedVendorId === 'all' ? 'All_Vendors' : (vendors.find((v) => v.id === selectedVendorId)?.name || 'Vendor');
    exportToCSV(orderLines, vendorLabel, toInputDate(orderDate));
  };

  const handlePDF = () => {
    if (!isWeb) return;
    const vendorLabel = selectedVendorId === 'all' ? 'All Vendors' : (vendors.find((v) => v.id === selectedVendorId)?.name || 'Vendor');
    const dtc = orderLines.length > 0 ? orderLines[0].daysToCover : 0;
    exportToPDF(orderLines, vendorLabel, currentStore.name, orderDate, dtc);
  };

  return (
    <View style={[styles.container, { backgroundColor: C.bgTertiary }]}>
      {/* Title bar */}
      <View style={[styles.titleBar, { backgroundColor: C.textPrimary }]}>
        <View>
          <Text style={[styles.brandName, { color: C.white }]}>2AM</Text>
          <Text style={styles.reportTitle}>Daily Replenishment Guide</Text>
          <Text style={styles.reportSub}>
            {currentStore.name} · {formatDate(orderDate)}
          </Text>
        </View>
      </View>

      {/* Filters: Vendor + Date */}
      <View style={styles.filterRow}>
        <View style={styles.filterGroup}>
          <Text style={[styles.filterLabel, { color: C.textTertiary }]}>Vendor</Text>
          <View style={styles.pillRow}>
            <TouchableOpacity
              style={[styles.pill, { backgroundColor: C.bgPrimary, borderColor: C.borderMedium }, selectedVendorId === 'all' && styles.pillActive, selectedVendorId === 'all' && { backgroundColor: C.textPrimary, borderColor: C.textPrimary }]}
              onPress={() => setSelectedVendorId('all')}
            >
              <Text style={[styles.pillText, { color: C.textSecondary }, selectedVendorId === 'all' && styles.pillTextActive]}>
                All Vendors
              </Text>
            </TouchableOpacity>
            {activeVendors.map((v) => (
              <TouchableOpacity
                key={v.id}
                style={[styles.pill, { backgroundColor: C.bgPrimary, borderColor: C.borderMedium }, selectedVendorId === v.id && styles.pillActive, selectedVendorId === v.id && { backgroundColor: C.textPrimary, borderColor: C.textPrimary }]}
                onPress={() => setSelectedVendorId(v.id)}
              >
                <Text style={[styles.pillText, { color: C.textSecondary }, selectedVendorId === v.id && styles.pillTextActive]}>
                  {v.name}
                </Text>
              </TouchableOpacity>
            ))}
          </View>
        </View>

        <View style={styles.filterGroup}>
          <Text style={[styles.filterLabel, { color: C.textTertiary }]}>Order Date</Text>
          {isWeb ? (
            <input
              type="date"
              value={dateInput}
              onChange={(e: any) => setDateInput(e.target.value)}
              style={{
                padding: '8px 12px',
                borderRadius: 8,
                border: `1px solid ${C.borderMedium}`,
                fontSize: 13,
                fontFamily: 'inherit',
                backgroundColor: C.bgSecondary,
                color: C.textPrimary,
                outline: 'none',
              }}
            />
          ) : (
            <TextInput
              style={[styles.dateInput, { color: C.textPrimary, backgroundColor: C.bgSecondary, borderColor: C.borderMedium }]}
              value={dateInput}
              onChangeText={setDateInput}
              placeholder="YYYY-MM-DD"
              placeholderTextColor={C.textTertiary}
            />
          )}
        </View>
      </View>

      {/* Summary KPIs + export */}
      <View style={styles.summaryRow}>
        <View style={styles.summaryCards}>
          <View style={[styles.kpi, { backgroundColor: C.bgPrimary, borderColor: C.borderLight }]}>
            <Text style={[styles.kpiValue, { color: C.textPrimary }]}>{orderLines.length}</Text>
            <Text style={[styles.kpiLabel, { color: C.textTertiary }]}>Items to order</Text>
          </View>
          <View style={[styles.kpi, { backgroundColor: C.bgPrimary, borderColor: C.borderLight }]}>
            <Text style={[styles.kpiValue, { color: C.textPrimary }]}>{Object.keys(vendorGroups).length}</Text>
            <Text style={[styles.kpiLabel, { color: C.textTertiary }]}>Vendors</Text>
          </View>
          <View style={[styles.kpi, { backgroundColor: C.bgPrimary, borderColor: C.borderLight }]}>
            <Text style={[styles.kpiValue, { color: C.danger }]}>${totalCost.toFixed(2)}</Text>
            <Text style={[styles.kpiLabel, { color: C.textTertiary }]}>Est. total cost</Text>
          </View>
        </View>

        {isWeb && (
          <View style={styles.exportRow}>
            <TouchableOpacity style={[styles.exportBtn, { borderColor: C.success, backgroundColor: C.successBg }]} onPress={handleCSV}>
              <Ionicons name="document-text-outline" size={16} color={C.success} />
              <Text style={[styles.exportBtnText, { color: C.success }]}>Download CSV</Text>
            </TouchableOpacity>
            <TouchableOpacity style={[styles.exportBtn, styles.exportBtnPdf, { borderColor: C.textPrimary, backgroundColor: C.textPrimary }]} onPress={handlePDF}>
              <Ionicons name="download-outline" size={16} color={C.bgPrimary} />
              <Text style={[styles.exportBtnText, { color: C.bgPrimary }]}>Download PDF</Text>
            </TouchableOpacity>
          </View>
        )}
      </View>

      {/* Order table grouped by vendor */}
      <WebScrollView id="order-report-scroll" contentContainerStyle={styles.list}>
        {orderLines.length === 0 ? (
          <View style={styles.emptyBox}>
            <Ionicons name="checkmark-circle" size={40} color={C.success} />
            <Text style={[styles.emptyTitle, { color: C.textPrimary }]}>All stocked up!</Text>
            <Text style={[styles.emptyText, { color: C.textTertiary }]}>All items are at or above dynamic par level for this order date.</Text>
          </View>
        ) : (
          Object.entries(vendorGroups).map(([vendorName, { vendor, lines, daysToCover }]) => {
            const vendorTotal = lines.reduce((s, l) => s + l.estimatedCost, 0);
            const deliveryInfo = vendor?.deliveryDays?.join(', ') || 'N/A';
            return (
              <View key={vendorName} style={[styles.vendorSection, { backgroundColor: C.bgPrimary, borderColor: C.borderLight }]}>
                <View style={[styles.vendorHeader, { backgroundColor: C.bgSecondary, borderBottomColor: C.borderLight }]}>
                  <View style={[styles.vendorIcon, { backgroundColor: C.bgPrimary, borderColor: C.borderLight }]}>
                    <Ionicons name="business-outline" size={14} color={C.textSecondary} />
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text style={[styles.vendorName, { color: C.textPrimary }]}>{vendorName}</Text>
                    <Text style={[styles.vendorSchedule, { color: C.textTertiary }]}>
                      Delivers: {deliveryInfo} · {daysToCover} days coverage
                    </Text>
                  </View>
                  <Text style={[styles.vendorCount, { color: C.textTertiary }]}>{lines.length} items · ${vendorTotal.toFixed(2)}</Text>
                </View>

                {/* Table header */}
                <View style={[styles.tableHead, { borderBottomColor: C.borderMedium }]}>
                  <Text style={[styles.th, { flex: 2.2, color: C.textTertiary }]}>Item</Text>
                  <Text style={[styles.th, { flex: 0.8, textAlign: 'center', color: C.textTertiary }]}>Daily Use</Text>
                  <Text style={[styles.th, { flex: 0.7, textAlign: 'center', color: C.textTertiary }]}>Days</Text>
                  <Text style={[styles.th, { flex: 0.9, textAlign: 'center', color: C.textTertiary }]}>Target Par</Text>
                  <Text style={[styles.th, { flex: 0.8, textAlign: 'center', color: C.textTertiary }]}>EOD Rem.</Text>
                  <Text style={[styles.th, { flex: 0.8, textAlign: 'center', color: C.textTertiary }]}>Order Qty</Text>
                  <Text style={[styles.th, { flex: 1, textAlign: 'right', color: C.textTertiary }]}>Est. Cost</Text>
                </View>

                {/* Table rows */}
                {lines.map((line, idx) => (
                  <View
                    key={line.itemId}
                    style={[styles.tableRow, { borderBottomColor: C.borderLight }, idx % 2 === 1 && styles.tableRowAlt, idx % 2 === 1 && { backgroundColor: C.bgSecondary + '80' }]}
                  >
                    <View style={{ flex: 2.2 }}>
                      <Text style={[styles.td, { color: C.textPrimary }]}>{line.itemName}</Text>
                      <Text style={[styles.tdSub, { color: C.textTertiary }]}>{line.category} · {line.unit}</Text>
                    </View>
                    <Text style={[styles.td, { flex: 0.8, textAlign: 'center', color: C.textPrimary }]}>
                      {line.dailyUsage}
                    </Text>
                    <Text style={[styles.td, { flex: 0.7, textAlign: 'center', color: C.textPrimary }]}>
                      {line.daysToCover}
                    </Text>
                    <Text style={[styles.td, { flex: 0.9, textAlign: 'center', color: C.info }]}>
                      {line.dynamicPar}
                    </Text>
                    <Text style={[styles.td, { flex: 0.8, textAlign: 'center', color: C.textPrimary }]}>
                      {line.eodRemaining}
                    </Text>
                    <Text style={[styles.td, styles.orderQty, { flex: 0.8, textAlign: 'center', color: C.danger }]}>
                      {line.orderQuantity}
                    </Text>
                    <Text style={[styles.td, { flex: 1, textAlign: 'right', color: C.textPrimary }]}>
                      ${line.estimatedCost.toFixed(2)}
                    </Text>
                  </View>
                ))}
              </View>
            );
          })
        )}
      </WebScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bgTertiary },

  // Title bar
  titleBar: {
    backgroundColor: Colors.textPrimary, padding: Spacing.lg,
    paddingTop: Spacing.xl, paddingBottom: Spacing.xl,
  },
  brandName: {
    fontSize: FontSize.xl, fontWeight: '700', color: Colors.white,
    letterSpacing: 1,
  },
  reportTitle: {
    fontSize: FontSize.sm, color: 'rgba(255,255,255,0.7)',
    marginTop: 2, fontWeight: '500',
  },
  reportSub: {
    fontSize: FontSize.xs, color: 'rgba(255,255,255,0.5)', marginTop: 4,
  },

  // Filters
  filterRow: {
    padding: Spacing.lg, paddingBottom: Spacing.sm,
    gap: Spacing.md,
  },
  filterGroup: { gap: 6 },
  filterLabel: {
    fontSize: FontSize.xs, fontWeight: '600', color: Colors.textTertiary,
    textTransform: 'uppercase', letterSpacing: 0.5,
  },
  pillRow: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  pill: {
    paddingHorizontal: Spacing.md, paddingVertical: 6,
    borderRadius: Radius.round, backgroundColor: Colors.bgPrimary,
    borderWidth: 1, borderColor: Colors.borderMedium,
  },
  pillActive: {
    backgroundColor: Colors.textPrimary, borderColor: Colors.textPrimary,
  },
  pillText: { fontSize: FontSize.sm, color: Colors.textSecondary, fontWeight: '500' },
  pillTextActive: { color: Colors.bgPrimary },
  dateInput: {
    backgroundColor: Colors.bgPrimary, borderRadius: Radius.md,
    borderWidth: 1, borderColor: Colors.borderMedium,
    paddingHorizontal: Spacing.md, paddingVertical: 8,
    fontSize: FontSize.base, color: Colors.textPrimary, width: 160,
  },

  // Summary
  summaryRow: { padding: Spacing.lg, paddingBottom: Spacing.sm },
  summaryCards: { flexDirection: 'row', gap: Spacing.sm, marginBottom: Spacing.md },
  kpi: {
    flex: 1, backgroundColor: Colors.bgPrimary, borderRadius: Radius.md,
    padding: Spacing.md, alignItems: 'center',
    borderWidth: 0.5, borderColor: Colors.borderLight,
  },
  kpiValue: { fontSize: FontSize.xl, fontWeight: '700', color: Colors.textPrimary },
  kpiLabel: { fontSize: FontSize.xs, color: Colors.textTertiary, marginTop: 2 },

  // Export buttons
  exportRow: { flexDirection: 'row', gap: Spacing.sm },
  exportBtn: {
    flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 6, paddingVertical: 10, borderRadius: Radius.md,
    borderWidth: 1, borderColor: Colors.success, backgroundColor: Colors.successBg,
  },
  exportBtnPdf: {
    borderColor: Colors.textPrimary, backgroundColor: Colors.textPrimary,
  },
  exportBtnText: { fontSize: FontSize.sm, fontWeight: '600' },

  // List
  list: { paddingHorizontal: Spacing.lg, paddingBottom: Spacing.xxxl },

  // Vendor section
  vendorSection: {
    backgroundColor: Colors.bgPrimary, borderRadius: Radius.lg,
    marginTop: Spacing.md, borderWidth: 0.5, borderColor: Colors.borderLight,
    overflow: 'hidden',
  },
  vendorHeader: {
    flexDirection: 'row', alignItems: 'center', gap: Spacing.sm,
    padding: Spacing.md, backgroundColor: Colors.bgSecondary,
    borderBottomWidth: 0.5, borderBottomColor: Colors.borderLight,
  },
  vendorIcon: {
    width: 28, height: 28, borderRadius: 6, backgroundColor: Colors.bgPrimary,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 0.5, borderColor: Colors.borderLight,
  },
  vendorName: { fontSize: FontSize.sm, fontWeight: '600', color: Colors.textPrimary },
  vendorSchedule: { fontSize: FontSize.xs, color: Colors.textTertiary, marginTop: 1 },
  vendorCount: { fontSize: FontSize.xs, color: Colors.textTertiary },

  // Table
  tableHead: {
    flexDirection: 'row', paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm,
    borderBottomWidth: 0.5, borderBottomColor: Colors.borderMedium,
  },
  th: {
    fontSize: 9, fontWeight: '600', color: Colors.textTertiary,
    textTransform: 'uppercase', letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm,
    borderBottomWidth: 0.5, borderBottomColor: Colors.borderLight,
  },
  tableRowAlt: { backgroundColor: Colors.bgSecondary + '80' },
  td: { fontSize: FontSize.sm, color: Colors.textPrimary },
  tdSub: { fontSize: 9, color: Colors.textTertiary, marginTop: 1 },
  orderQty: { fontWeight: '700', color: Colors.danger },

  // Empty
  emptyBox: { alignItems: 'center', paddingVertical: Spacing.xxxl * 2 },
  emptyTitle: { fontSize: FontSize.lg, fontWeight: '600', color: Colors.textPrimary, marginTop: Spacing.md },
  emptyText: { fontSize: FontSize.sm, color: Colors.textTertiary, marginTop: 4 },
});
