// src/screens/OrdersScreen.tsx
// Smart Ordering Hub — weekly schedule + live suggested order detail
import React, { useState, useMemo, useCallback } from 'react';
import {
  View, Text, ScrollView, StyleSheet, TouchableOpacity,
  Modal, TextInput, Alert, Platform,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useStore } from '../store/useStore';
import { WebScrollView } from '../components/WebScrollView';
import { Colors, useColors, Spacing, Radius, FontSize } from '../theme/colors';
import { OrderDayVendor, Vendor } from '../types';
import { calculateDynamicOrder, DynamicOrderLine } from '../lib/orderCalculator';
import { getBusinessTodayParts, computeWeekdayDateISO } from '../utils/businessDay';
import { getNowInTZ } from '../utils/timezone';
import { TimezoneBar } from '../components/TimezoneBar';

const isWeb = Platform.OS === 'web';

const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const DAY_FULL = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

function getDayName(tz: string): string {
  return new Date().toLocaleDateString('en-US', { timeZone: tz, weekday: 'long' });
}

function getDateForDay(dayName: string, tz: string): string {
  const now = getNowInTZ(tz);
  const currentDayIdx = now.getDay();
  const targetIdx = DAY_FULL.indexOf(dayName);
  const diff = targetIdx - currentDayIdx;
  const target = new Date(now);
  target.setDate(now.getDate() + diff);
  return target.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

function getDateObjectForDay(dayName: string, tz: string): Date {
  const now = getNowInTZ(tz);
  const currentDayIdx = now.getDay();
  const targetIdx = DAY_FULL.indexOf(dayName);
  const diff = targetIdx - currentDayIdx;
  const target = new Date(now);
  target.setDate(now.getDate() + diff);
  return target;
}

function formatDate(d: Date) {
  return d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' });
}

function toISODate(d: Date) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

// ── CSV Export ───────────────────────────────────────────────
function exportToCSV(data: DynamicOrderLine[], vendorName: string, dateStr: string) {
  const headers = ['Item Name', 'Category', 'Unit', 'Daily Usage', 'Days to Cover', 'Safety Stock', 'Target Par', 'EOD Remaining', 'Order Qty', 'Cost/Unit', 'Est. Cost'];
  const rows = data.map((d) => [
    d.itemName, d.category, d.unit,
    d.dailyUsage, d.daysToCover, d.safetyStock, d.dynamicPar,
    d.eodRemaining, d.orderQuantity,
    d.costPerUnit.toFixed(2), d.estimatedCost.toFixed(2),
  ]);
  const csv = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `2AM_Order_${vendorName.replace(/\s/g, '_')}_${dateStr}.csv`;
  link.click();
  URL.revokeObjectURL(url);
}

// ── PDF Export ───────────────────────────────────────────────
async function exportToPDF(data: DynamicOrderLine[], vendorName: string, storeName: string, orderDate: Date) {
  const { default: jsPDF } = await import('jspdf');
  await import('jspdf-autotable');

  const dtc = data.length > 0 ? data[0].daysToCover : 0;
  const dateStr = formatDate(orderDate);
  const doc = new jsPDF();

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('2AM', 14, 20);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Daily Replenishment Guide', 14, 28);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Store: ${storeName}  |  Vendor: ${vendorName}  |  Order Date: ${dateStr}`, 14, 35);
  doc.text(`${data.length} items  |  ${dtc} days coverage  |  Est. total: $${data.reduce((s, d) => s + d.estimatedCost, 0).toFixed(2)}`, 14, 41);

  (doc as any).autoTable({
    startY: 48,
    head: [['Item', 'Category', 'Unit', 'Daily Use', 'Days', 'Target Par', 'EOD Rem.', 'Order Qty', 'Est. Cost']],
    body: data.map((d) => [
      d.itemName, d.category, d.unit,
      d.dailyUsage, d.daysToCover, d.dynamicPar,
      d.eodRemaining, d.orderQuantity,
      `$${d.estimatedCost.toFixed(2)}`,
    ]),
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [26, 26, 24], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [245, 245, 243] },
    columnStyles: {
      3: { halign: 'center' }, 4: { halign: 'center' }, 5: { halign: 'center' },
      6: { halign: 'center' },
      7: { halign: 'center', fontStyle: 'bold', textColor: [121, 31, 31] },
      8: { halign: 'right' },
    },
  });

  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by 2AM Inventory Management System', 14, pageHeight - 10);
  doc.save(`2AM_Order_${vendorName.replace(/\s/g, '_')}_${toISODate(orderDate)}.pdf`);
}

// ═════════════════════════════════════════════════════════════
// ── Main Component ───────────────────────────────────────────
// ═════════════════════════════════════════════════════════════
export default function OrdersScreen() {
  const {
    currentUser, currentStore, inventory, vendors: allVendors,
    orderSchedule, orderSubmissions, eodSubmissions,
    setOrderSchedule, submitOrder, timezone,
  } = useStore();
  const C = useColors();
  const isAdmin = currentUser?.role === 'admin';
  // Business-day aware "today" — rolls over at 3 AM local so late-night closing
  // shifts stay on the previous calendar day's entries.
  const businessToday = getBusinessTodayParts(timezone);
  const todayName = businessToday.weekday;
  const todayISO = businessToday.dateISO;

  // ── Schedule edit state ──
  const [showEditModal, setShowEditModal] = useState(false);
  const [editDay, setEditDay] = useState('');
  const [editVendors, setEditVendors] = useState<OrderDayVendor[]>([]);

  // ── Detail modal state ──
  const [detailOpen, setDetailOpen] = useState(false);
  const [detailDay, setDetailDay] = useState('');
  const [detailVendorName, setDetailVendorName] = useState('');

  // ── Derived data ──
  const storeInventory = useMemo(
    () => inventory.filter((i) => i.storeId === currentStore.id),
    [inventory, currentStore.id],
  );

  // Pre-compute order summaries for all vendor-day combos (EOD-based)
  const vendorOrderSummaries = useMemo(() => {
    const summaries: Record<string, { itemCount: number; totalCost: number }> = {};
    DAYS.forEach((day) => {
      (orderSchedule[day] || []).forEach((sv) => {
        const key = `${day}::${sv.vendorName}`;
        const vendor = sv.vendorId
          ? allVendors.find((v) => v.id === sv.vendorId)
          : allVendors.find((v) => v.name.toLowerCase() === sv.vendorName.toLowerCase());
        if (!vendor) { summaries[key] = { itemCount: 0, totalCost: 0 }; return; }
        const date = getDateObjectForDay(day, timezone);
        const lines = calculateDynamicOrder(storeInventory, vendor, date);
        summaries[key] = {
          itemCount: lines.filter((l) => l.orderQuantity > 0).length,
          totalCost: lines.reduce((s, l) => s + l.estimatedCost, 0),
        };
      });
    });
    return summaries;
  }, [orderSchedule, allVendors, storeInventory, timezone]);

  const weekSubmissions = useMemo(
    () => orderSubmissions.filter((s) => s.storeId === currentStore.id),
    [orderSubmissions, currentStore.id],
  );

  // For each weekly day-card, compare against the DAY CARD's own calendar date
  // (not todayISO). A submission is "belongs to this card" when its
  // reference_date matches the card's date. This makes the "Submitted" pill
  // sticky across refresh and across midnight/day rollover.
  const isDaySubmitted = useCallback(
    (day: string, vendorName: string) => {
      const dayISO = computeWeekdayDateISO(day, timezone);
      return weekSubmissions.some(
        (s) => s.vendorName === vendorName && s.date === dayISO,
      );
    },
    [weekSubmissions, timezone],
  );

  // ── Detail modal computed order lines ──
  const detailDate = useMemo(
    () => detailDay ? getDateObjectForDay(detailDay, timezone) : new Date(),
    [detailDay, timezone],
  );

  const detailVendor: Vendor | undefined = useMemo(() => {
    // Try vendorId first (from schedule entry), fall back to name
    const schedEntry = (orderSchedule[detailDay] || []).find((v) => v.vendorName === detailVendorName);
    if (schedEntry?.vendorId) {
      const byId = allVendors.find((v) => v.id === schedEntry.vendorId);
      if (byId) return byId;
    }
    return allVendors.find((v) => v.name.toLowerCase() === detailVendorName.toLowerCase());
  }, [allVendors, detailVendorName, detailDay, orderSchedule]);

  // Item IDs the user has counted in EOD today (any submission for this store)
  const todayEODItemIds = useMemo(() => {
    const ids = new Set<string>();
    eodSubmissions
      .filter((s) => s.storeId === currentStore.id && s.date === todayISO)
      .forEach((s) => s.entries.forEach((e) => ids.add(e.itemId)));
    return ids;
  }, [eodSubmissions, currentStore.id, todayISO]);

  const detailLines: DynamicOrderLine[] = useMemo(() => {
    if (!detailVendor || !detailOpen) return [];
    // Include zero-order rows so we can surface today's EOD counts that are at/above par
    const all = calculateDynamicOrder(storeInventory, detailVendor, detailDate, { includeZeroOrder: true });
    // Show items that either need ordering OR were counted today (above-par confirmations)
    return all.filter((l) => l.orderQuantity > 0 || todayEODItemIds.has(l.itemId));
  }, [detailVendor, detailOpen, storeInventory, detailDate, todayEODItemIds]);

  // Lines the user actually needs to order (excludes above-par "confirmation" rows)
  const detailOrderLines = useMemo(
    () => detailLines.filter((l) => l.orderQuantity > 0),
    [detailLines],
  );

  const detailTotalCost = useMemo(
    () => detailLines.reduce((s, l) => s + l.estimatedCost, 0),
    [detailLines],
  );

  const detailDaysCover = detailLines.length > 0 ? detailLines[0].daysToCover : 0;
  const detailSubmitted = isDaySubmitted(detailDay, detailVendorName);
  const detailSubmission = weekSubmissions.find(
    (s) => s.vendorName === detailVendorName && s.date === computeWeekdayDateISO(detailDay, timezone),
  );

  // ── Handlers ──
  const openDetail = (day: string, vendorName: string) => {
    setDetailDay(day);
    setDetailVendorName(vendorName);
    setDetailOpen(true);
  };

  const openEdit = (day: string) => {
    setEditDay(day);
    setEditVendors([...(orderSchedule[day] || [])]);
    setShowEditModal(true);
  };

  const addVendorRow = () => {
    setEditVendors([...editVendors, { vendorName: '', deliveryDay: 'Wednesday' }]);
  };

  const removeVendorRow = (idx: number) => {
    setEditVendors(editVendors.filter((_, i) => i !== idx));
  };

  const updateVendorRow = (idx: number, field: keyof OrderDayVendor, value: string) => {
    setEditVendors(editVendors.map((v, i) => (i === idx ? { ...v, [field]: value } : v)));
  };

  const selectVendorForRow = (idx: number, vendor: Vendor) => {
    setEditVendors(editVendors.map((v, i) =>
      i === idx ? {
        ...v,
        vendorName: vendor.name,
        vendorId: vendor.id,
        deliveryDay: (vendor as any).deliveryDays?.[0] || v.deliveryDay,
      } : v
    ));
  };

  const saveSchedule = () => {
    setOrderSchedule(editDay, editVendors.filter((v) => v.vendorName.trim()));
    setShowEditModal(false);
  };

  const handleMarkSubmitted = () => {
    // Stamp the submission with the DAY CARD's calendar date, not "now".
    // Without this, a Thursday-card submission marked at 3 AM Friday would
    // carry Friday's date and the Thursday pill would never match.
    const referenceDate = computeWeekdayDateISO(detailDay, timezone);
    submitOrder({
      storeId: currentStore.id,
      day: detailDay,
      date: referenceDate,
      vendorName: detailVendorName,
      submittedBy: currentUser?.name || '',
      submittedAt: getNowInTZ(timezone).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }),
    });
    setDetailOpen(false);
  };

  const handleCSV = () => {
    if (!isWeb || detailOrderLines.length === 0) return;
    exportToCSV(detailOrderLines, detailVendorName, toISODate(detailDate));
  };

  const handlePDF = () => {
    if (!isWeb || detailOrderLines.length === 0) return;
    exportToPDF(detailOrderLines, detailVendorName, currentStore.name, detailDate);
  };

  // ═════════════════════════════════════════════════════════════
  // ── RENDER ─────────────────────────────────────────────────
  // ═════════════════════════════════════════════════════════════
  return (
    <View style={[styles.container, { backgroundColor: C.bgTertiary }]}>
      <TimezoneBar />

      {/* ── Weekly schedule ── */}
      <WebScrollView id="orders-scroll" contentContainerStyle={styles.list}>
        {DAYS.map((day) => {
          const vendors = orderSchedule[day] || [];
          const isToday = day === todayName;
          const dateStr = getDateForDay(day, timezone);

          return (
            <View key={day} style={[styles.dayCard, { backgroundColor: C.bgPrimary, borderColor: C.borderLight }, isToday && styles.dayCardToday, isToday && { borderColor: C.info }]}>
              <View style={styles.dayHeader}>
                <View style={styles.dayHeaderLeft}>
                  <Text style={[styles.dayName, { color: C.textPrimary }, isToday && styles.dayNameToday, isToday && { color: C.info }]}>{day}</Text>
                  <Text style={[styles.dayDate, { color: C.textTertiary }]}>{dateStr}</Text>
                  {isToday && (
                    <View style={[styles.todayBadge, { backgroundColor: C.infoBg }]}>
                      <Text style={[styles.todayBadgeText, { color: C.info }]}>Today</Text>
                    </View>
                  )}
                </View>
                {isAdmin && (
                  <TouchableOpacity style={[styles.editBtn, { backgroundColor: C.bgSecondary, borderColor: C.borderLight }]} onPress={() => openEdit(day)}>
                    <Ionicons name="create-outline" size={14} color={C.textSecondary} />
                  </TouchableOpacity>
                )}
              </View>

              {vendors.length === 0 ? (
                <View style={styles.noVendors}>
                  <Text style={[styles.noVendorsText, { color: C.textTertiary }]}>No orders scheduled</Text>
                  {isAdmin && (
                    <TouchableOpacity onPress={() => openEdit(day)}>
                      <Text style={[styles.addVendorLink, { color: C.info }]}>+ Add vendor</Text>
                    </TouchableOpacity>
                  )}
                </View>
              ) : (
                vendors.map((vendor, idx) => {
                  const submitted = isDaySubmitted(day, vendor.vendorName);
                  const needsAttention = isToday && !submitted;

                  return (
                    <TouchableOpacity
                      key={idx}
                      style={[styles.vendorRow, { borderTopColor: C.borderLight }]}
                      activeOpacity={0.6}
                      onPress={() => openDetail(day, vendor.vendorName)}
                    >
                      <View style={styles.vendorInfo}>
                        {needsAttention && (
                          <Ionicons name="alert-circle" size={18} color={C.warning} style={{ marginRight: 6 }} />
                        )}
                        {submitted && (
                          <Ionicons name="checkmark-circle" size={18} color={C.success} style={{ marginRight: 6 }} />
                        )}
                        <View style={{ flex: 1 }}>
                          <Text style={[styles.vendorName, { color: C.textPrimary }]}>{vendor.vendorName}</Text>
                          <Text style={[styles.deliveryText, { color: C.textTertiary }]}>Delivery by {vendor.deliveryDay}</Text>
                          {(() => {
                            const summary = vendorOrderSummaries[`${day}::${vendor.vendorName}`];
                            if (!summary || summary.itemCount === 0) return (
                              <Text style={{ fontSize: 10, color: C.success, fontWeight: '500', marginTop: 2 }}>All stocked</Text>
                            );
                            return (
                              <Text style={{ fontSize: 10, color: C.danger, fontWeight: '500', marginTop: 2 }}>
                                {summary.itemCount} items · ${summary.totalCost.toFixed(2)}
                              </Text>
                            );
                          })()}
                        </View>
                      </View>
                      {submitted ? (
                        <View style={[styles.submittedBadge, { backgroundColor: C.successBg }]}>
                          <Text style={[styles.submittedText, { color: C.success }]}>Submitted</Text>
                        </View>
                      ) : isToday ? (
                        <View style={[styles.pendingBadge, { backgroundColor: C.warningBg }]}>
                          <Text style={[styles.pendingText, { color: C.warning }]}>Pending</Text>
                        </View>
                      ) : null}
                      <Ionicons name="chevron-forward" size={16} color={C.textTertiary} style={{ marginLeft: 8 }} />
                    </TouchableOpacity>
                  );
                })
              )}
            </View>
          );
        })}
      </WebScrollView>

      {/* ═══════════════════════════════════════════════════════ */}
      {/* ── DETAIL MODAL — Suggested Order for Vendor ──────── */}
      {/* ═══════════════════════════════════════════════════════ */}
      <Modal visible={detailOpen} animationType="slide" presentationStyle="pageSheet">
        <View style={[styles.modal, { backgroundColor: C.bgPrimary }]}>
          {/* Header */}
          <View style={[styles.detailHeader, { borderBottomColor: C.borderLight }]}>
            <View style={{ flex: 1 }}>
              <Text style={[styles.detailTitle, { color: C.textPrimary }]}>{detailVendorName}</Text>
              <Text style={[styles.detailSubtitle, { color: C.textTertiary }]}>
                {detailDay} · {formatDate(detailDate)} · {currentStore.name}
              </Text>
            </View>
            <View style={styles.detailHeaderActions}>
              {isWeb && detailOrderLines.length > 0 && (
                <>
                  <TouchableOpacity style={[styles.exportBtn, { borderColor: C.borderLight, backgroundColor: C.bgSecondary }]} onPress={handleCSV}>
                    <Ionicons name="download-outline" size={15} color={C.textSecondary} />
                    <Text style={[styles.exportBtnText, { color: C.textSecondary }]}>CSV</Text>
                  </TouchableOpacity>
                  <TouchableOpacity style={[styles.exportBtn, { borderColor: C.borderLight, backgroundColor: C.bgSecondary }]} onPress={handlePDF}>
                    <Ionicons name="document-text-outline" size={15} color={C.textSecondary} />
                    <Text style={[styles.exportBtnText, { color: C.textSecondary }]}>PDF</Text>
                  </TouchableOpacity>
                </>
              )}
              <TouchableOpacity style={[styles.closeBtn, { backgroundColor: C.bgSecondary, borderColor: C.borderLight }]} onPress={() => setDetailOpen(false)}>
                <Ionicons name="close" size={20} color={C.textSecondary} />
              </TouchableOpacity>
            </View>
          </View>

          {/* Summary stats */}
          <View style={[styles.statsRow, { borderBottomColor: C.borderLight }]}>
            <View style={[styles.statBox, { backgroundColor: C.bgSecondary, borderColor: C.borderLight }]}>
              <Text style={[styles.statValue, { color: C.textPrimary }]}>{detailOrderLines.length}</Text>
              <Text style={[styles.statLabel, { color: C.textTertiary }]}>Items</Text>
            </View>
            <View style={[styles.statBox, { backgroundColor: C.bgSecondary, borderColor: C.borderLight }]}>
              <Text style={[styles.statValue, { color: C.textPrimary }]}>{detailDaysCover}</Text>
              <Text style={[styles.statLabel, { color: C.textTertiary }]}>Days cover</Text>
            </View>
            <View style={[styles.statBox, { flex: 1.5, backgroundColor: C.bgSecondary, borderColor: C.borderLight }]}>
              <Text style={[styles.statValue, { color: C.danger }]}>
                ${detailTotalCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </Text>
              <Text style={[styles.statLabel, { color: C.textTertiary }]}>Est. total</Text>
            </View>
            {detailSubmitted && detailSubmission && (
              <View style={[styles.statBox, { backgroundColor: C.successBg, borderColor: C.borderLight }]}>
                <Text style={[styles.statValue, { color: C.success, fontSize: FontSize.sm }]}>
                  {detailSubmission.submittedAt}
                </Text>
                <Text style={[styles.statLabel, { color: C.textTertiary }]}>by {detailSubmission.submittedBy}</Text>
              </View>
            )}
          </View>

          {/* Order table */}
          <ScrollView style={{ flex: 1 }} contentContainerStyle={{ paddingBottom: 100 }}>
            {!detailVendor ? (
              <View style={styles.emptyDetail}>
                <Ionicons name="alert-circle-outline" size={40} color={C.textTertiary} />
                <Text style={[styles.emptyTitle, { color: C.textPrimary }]}>Vendor not found</Text>
                <Text style={[styles.emptyText, { color: C.textTertiary }]}>
                  "{detailVendorName}" doesn't match any vendor in your system.{'\n'}
                  Add this vendor under More &gt; Vendors and assign inventory items to it.
                </Text>
              </View>
            ) : detailLines.length === 0 ? (
              <View style={styles.emptyDetail}>
                <Ionicons name="checkmark-circle-outline" size={40} color={C.success} />
                <Text style={[styles.emptyTitle, { color: C.textPrimary }]}>No items to order</Text>
                <Text style={[styles.emptyText, { color: C.textTertiary }]}>
                  All {detailVendorName} items are sufficiently stocked for the next {detailDaysCover} days.
                </Text>
              </View>
            ) : (
              <>
                {/* Table header */}
                <View style={[styles.tableHeader, { backgroundColor: C.bgSecondary, borderBottomColor: C.borderLight }]}>
                  <Text style={[styles.th, { flex: 2.5, color: C.textSecondary }]}>Item</Text>
                  <Text style={[styles.th, styles.thCenter, { color: C.textSecondary }]}>EOD</Text>
                  <Text style={[styles.th, styles.thCenter, { color: C.textSecondary }]}>Par</Text>
                  <Text style={[styles.th, styles.thCenter, { fontWeight: '700', color: C.textSecondary }]}>Order</Text>
                  <Text style={[styles.th, styles.thRight, { color: C.textSecondary }]}>Cost</Text>
                </View>

                {/* Table rows */}
                {detailLines.map((line, idx) => {
                  // Above-par rows are the "you counted today and you're stocked" confirmations
                  const isAbovePar = line.orderQuantity === 0;
                  // Build case breakdown label (only relevant for below-par rows)
                  const orderLabel = line.hasCaseInfo
                    ? (line.cases > 0 && line.looseUnits > 0
                        ? `${line.cases} cs + ${line.looseUnits} ea`
                        : line.cases > 0
                          ? `${line.cases} cs`
                          : `${line.looseUnits} ea`)
                    : `${line.orderQuantity} ${line.unit}`;
                  const rowBg = isAbovePar
                    ? C.successBg
                    : (idx % 2 === 0 ? C.bgTertiary : undefined);
                  return (
                    <View key={line.itemId} style={[styles.tableRow, { borderBottomColor: C.borderLight }, rowBg ? { backgroundColor: rowBg } : null]}>
                      <View style={{ flex: 2.5 }}>
                        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 4, flexWrap: 'wrap' }}>
                          <Text style={[styles.tdName, { color: C.textPrimary }]}>{line.itemName}</Text>
                          {!line.hasCaseInfo && (
                            <View style={{ backgroundColor: C.warningBg, paddingHorizontal: 4, paddingVertical: 1, borderRadius: 3 }}>
                              <Text style={{ fontSize: 8, color: C.warning, fontWeight: '600' }}>⚠ No case info</Text>
                            </View>
                          )}
                        </View>
                        <Text style={[styles.tdMeta, { color: C.textTertiary }]}>{line.category} · {line.unit}</Text>
                      </View>
                      <Text style={[styles.td, styles.tdCenter, { color: C.textPrimary }]}>{line.eodRemaining}</Text>
                      <View style={{ flex: 1, alignItems: 'center' }}>
                        <Text style={{ fontSize: FontSize.sm, color: C.textPrimary, textAlign: 'center' }}>{line.dynamicPar} {line.unit}</Text>
                        {line.hasCaseInfo && line.dynamicPar >= line.caseQty && (() => {
                          const parCases = Math.floor(line.dynamicPar / line.caseQty);
                          const parEach = line.dynamicPar - (parCases * line.caseQty);
                          const breakdown = parEach > 0 ? `${parCases} cs + ${parEach} ea` : `${parCases} cs`;
                          return <Text style={{ fontSize: 10, color: C.textTertiary }}>{breakdown}</Text>;
                        })()}
                      </View>
                      <View style={styles.orderQtyCell}>
                        {isAbovePar ? (
                          <Text style={[styles.orderQtyText, { color: C.success, backgroundColor: C.successBg }]}>✓ At par</Text>
                        ) : (
                          <Text style={[styles.orderQtyText, { color: C.danger, backgroundColor: C.dangerBg }]}>{orderLabel}</Text>
                        )}
                      </View>
                      <Text style={[styles.td, styles.tdRight, { color: isAbovePar ? C.textTertiary : C.textPrimary }]}>
                        {isAbovePar ? '—' : `$${line.estimatedCost.toFixed(2)}`}
                      </Text>
                    </View>
                  );
                })}

                {/* Totals row */}
                <View style={[styles.totalRow, { backgroundColor: C.bgSecondary, borderTopColor: C.borderMedium }]}>
                  <Text style={[styles.totalLabel, { flex: 2.5, color: C.textSecondary }]}>
                    Total ({detailOrderLines.length} items)
                  </Text>
                  <Text style={[styles.totalLabel, { color: C.textSecondary }]} />
                  <Text style={[styles.totalLabel, { color: C.textSecondary }]} />
                  <Text style={[styles.totalValue, styles.tdCenter, { color: C.textPrimary }]}>
                    {detailLines.reduce((s, l) => s + l.orderQuantity, 0)}
                  </Text>
                  <Text style={[styles.totalValue, styles.tdRight, { color: C.textPrimary }]}>
                    ${detailTotalCost.toFixed(2)}
                  </Text>
                </View>
              </>
            )}
          </ScrollView>

          {/* Footer — Submit button */}
          <View style={[styles.detailFooter, { borderTopColor: C.borderLight, backgroundColor: C.bgPrimary }]}>
            {detailSubmitted ? (
              <View style={[styles.submittedFooter, { backgroundColor: C.successBg }]}>
                <Ionicons name="checkmark-circle" size={20} color={C.success} />
                <Text style={[styles.submittedFooterText, { color: C.success }]}>
                  Submitted by {detailSubmission?.submittedBy} at {detailSubmission?.submittedAt}
                </Text>
              </View>
            ) : (
              <TouchableOpacity style={[styles.markSubmittedBtn, { backgroundColor: C.success }]} onPress={handleMarkSubmitted}>
                <Ionicons name="checkmark-circle-outline" size={20} color={C.white} />
                <Text style={[styles.markSubmittedText, { color: C.bgPrimary }]}>Mark Order as Submitted</Text>
              </TouchableOpacity>
            )}
          </View>
        </View>
      </Modal>

      {/* ═══════════════════════════════════════════════════════ */}
      {/* ── EDIT SCHEDULE MODAL ───────────────────────────────  */}
      {/* ═══════════════════════════════════════════════════════ */}
      <Modal visible={showEditModal} animationType="slide" presentationStyle="pageSheet">
        <View style={[styles.modal, { backgroundColor: C.bgPrimary }]}>
          <View style={[styles.editModalHeader, { borderBottomColor: C.borderLight }]}>
            <Text style={[styles.editModalTitle, { color: C.textPrimary }]}>{editDay} - Vendors</Text>
            <TouchableOpacity onPress={() => setShowEditModal(false)}>
              <Text style={[styles.editModalCancel, { color: C.info }]}>Cancel</Text>
            </TouchableOpacity>
          </View>
          <ScrollView contentContainerStyle={styles.editModalBody}>
            {editVendors.map((vendor, idx) => (
              <View key={idx} style={[styles.vendorEditRow, { borderBottomColor: C.borderLight }]}>
                <View style={styles.vendorEditFields}>
                  <View style={styles.formField}>
                    <Text style={[styles.formLabel, { color: C.textSecondary }]}>Vendor</Text>
                    <ScrollView horizontal showsHorizontalScrollIndicator={false}>
                      <View style={styles.chipRow}>
                        {allVendors.map((v) => {
                          const isSelected = vendor.vendorName.toLowerCase() === v.name.toLowerCase() || vendor.vendorId === v.id;
                          return (
                            <TouchableOpacity
                              key={v.id}
                              style={[styles.chip, { backgroundColor: C.bgSecondary, borderColor: C.borderLight }, isSelected && { backgroundColor: C.textPrimary, borderColor: C.textPrimary }]}
                              onPress={() => selectVendorForRow(idx, v)}
                            >
                              <Text style={[styles.chipText, { color: C.textSecondary }, isSelected && { color: C.bgPrimary }]}>{v.name}</Text>
                            </TouchableOpacity>
                          );
                        })}
                      </View>
                    </ScrollView>
                    {!vendor.vendorName && (
                      <Text style={{ fontSize: 11, color: C.textTertiary, marginTop: 4 }}>Tap a vendor to select</Text>
                    )}
                  </View>
                  <View style={styles.formField}>
                    <Text style={[styles.formLabel, { color: C.textSecondary }]}>Delivery by</Text>
                    <ScrollView horizontal showsHorizontalScrollIndicator={false}>
                      <View style={styles.chipRow}>
                        {DAYS.map((d) => (
                          <TouchableOpacity
                            key={d}
                            style={[styles.chip, { backgroundColor: C.bgSecondary, borderColor: C.borderLight }, vendor.deliveryDay === d && styles.chipActive, vendor.deliveryDay === d && { backgroundColor: C.textPrimary, borderColor: C.textPrimary }]}
                            onPress={() => updateVendorRow(idx, 'deliveryDay', d)}
                          >
                            <Text style={[styles.chipText, { color: C.textSecondary }, vendor.deliveryDay === d && styles.chipTextActive, vendor.deliveryDay === d && { color: C.bgPrimary }]}>
                              {d.slice(0, 3)}
                            </Text>
                          </TouchableOpacity>
                        ))}
                      </View>
                    </ScrollView>
                  </View>
                </View>
                <TouchableOpacity style={[styles.removeBtn, { backgroundColor: C.dangerBg }]} onPress={() => removeVendorRow(idx)}>
                  <Ionicons name="trash-outline" size={16} color={C.danger} />
                </TouchableOpacity>
              </View>
            ))}

            <TouchableOpacity style={[styles.addRowBtn, { borderColor: C.borderLight }]} onPress={addVendorRow}>
              <Text style={[styles.addRowBtnText, { color: C.info }]}>+ Add vendor</Text>
            </TouchableOpacity>

            <TouchableOpacity style={[styles.saveBtn, { backgroundColor: C.textPrimary }]} onPress={saveSchedule}>
              <Text style={[styles.saveBtnText, { color: C.bgPrimary }]}>Save</Text>
            </TouchableOpacity>
          </ScrollView>
        </View>
      </Modal>

    </View>
  );
}

// ═════════════════════════════════════════════════════════════
// ── Styles ───────────────────────────────────────────────────
// ═════════════════════════════════════════════════════════════
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bgTertiary },

  // List
  list: { padding: Spacing.lg, paddingBottom: Spacing.xxxl },

  // Day card
  dayCard: { backgroundColor: Colors.bgPrimary, borderRadius: Radius.lg, padding: Spacing.md, marginBottom: Spacing.sm, borderWidth: 0.5, borderColor: Colors.borderLight },
  dayCardToday: { borderColor: Colors.info, borderWidth: 1.5 },
  dayHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: Spacing.sm },
  dayHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  dayName: { fontSize: FontSize.base, fontWeight: '600', color: Colors.textPrimary },
  dayNameToday: { color: Colors.info },
  dayDate: { fontSize: FontSize.xs, color: Colors.textTertiary },
  todayBadge: { backgroundColor: Colors.infoBg, paddingHorizontal: 8, paddingVertical: 2, borderRadius: Radius.round },
  todayBadgeText: { fontSize: 9, fontWeight: '600', color: Colors.info },
  editBtn: { width: 32, height: 32, borderRadius: 16, backgroundColor: Colors.bgSecondary, alignItems: 'center', justifyContent: 'center', borderWidth: 0.5, borderColor: Colors.borderLight },

  // No vendors
  noVendors: { paddingVertical: Spacing.sm, alignItems: 'center' },
  noVendorsText: { fontSize: FontSize.xs, color: Colors.textTertiary },
  addVendorLink: { fontSize: FontSize.xs, color: Colors.info, fontWeight: '500', marginTop: 4 },

  // Vendor row — now touchable
  vendorRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: Spacing.sm + 2, paddingHorizontal: 4, borderTopWidth: 0.5, borderTopColor: Colors.borderLight },
  vendorInfo: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  vendorName: { fontSize: FontSize.sm, fontWeight: '500', color: Colors.textPrimary },
  deliveryText: { fontSize: FontSize.xs, color: Colors.textTertiary, marginTop: 1 },
  submittedBadge: { backgroundColor: Colors.successBg, paddingHorizontal: 10, paddingVertical: 4, borderRadius: Radius.round },
  submittedText: { fontSize: FontSize.xs, color: Colors.success, fontWeight: '500' },
  pendingBadge: { backgroundColor: Colors.warningBg, paddingHorizontal: 10, paddingVertical: 4, borderRadius: Radius.round },
  pendingText: { fontSize: FontSize.xs, color: Colors.warning, fontWeight: '500' },

  // ── Modals shared ──
  modal: { flex: 1, backgroundColor: Colors.bgPrimary },

  // ── Detail Modal ──
  detailHeader: {
    flexDirection: 'row', alignItems: 'flex-start',
    padding: Spacing.lg, borderBottomWidth: 0.5, borderBottomColor: Colors.borderLight,
  },
  detailTitle: { fontSize: FontSize.lg, fontWeight: '700', color: Colors.textPrimary },
  detailSubtitle: { fontSize: FontSize.xs, color: Colors.textTertiary, marginTop: 2 },
  detailHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  exportBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 4,
    paddingHorizontal: 10, paddingVertical: 6,
    borderRadius: Radius.md, borderWidth: 0.5, borderColor: Colors.borderLight,
    backgroundColor: Colors.bgSecondary,
  },
  exportBtnText: { fontSize: FontSize.xs, fontWeight: '500', color: Colors.textSecondary },
  closeBtn: {
    width: 32, height: 32, borderRadius: 16,
    backgroundColor: Colors.bgSecondary, alignItems: 'center', justifyContent: 'center',
    borderWidth: 0.5, borderColor: Colors.borderLight,
  },

  // Stats row
  statsRow: {
    flexDirection: 'row', gap: 8, paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md,
    borderBottomWidth: 0.5, borderBottomColor: Colors.borderLight,
  },
  statBox: {
    flex: 1, backgroundColor: Colors.bgSecondary, borderRadius: Radius.md,
    padding: Spacing.sm, alignItems: 'center',
    borderWidth: 0.5, borderColor: Colors.borderLight,
  },
  statValue: { fontSize: FontSize.lg, fontWeight: '700', color: Colors.textPrimary },
  statLabel: { fontSize: 9, color: Colors.textTertiary, marginTop: 1 },

  // Table
  tableHeader: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: Spacing.lg, paddingVertical: Spacing.sm,
    backgroundColor: Colors.bgSecondary, borderBottomWidth: 0.5, borderBottomColor: Colors.borderLight,
  },
  th: { flex: 1, fontSize: FontSize.xs, fontWeight: '600', color: Colors.textSecondary },
  thCenter: { textAlign: 'center' },
  thRight: { textAlign: 'right' },

  tableRow: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: Spacing.lg, paddingVertical: Spacing.sm,
    borderBottomWidth: 0.5, borderBottomColor: Colors.borderLight,
  },
  tableRowAlt: { backgroundColor: Colors.bgTertiary },

  tdName: { fontSize: FontSize.sm, fontWeight: '500', color: Colors.textPrimary },
  tdMeta: { fontSize: 9, color: Colors.textTertiary, marginTop: 1 },
  td: { flex: 1, fontSize: FontSize.sm, color: Colors.textPrimary },
  tdCenter: { textAlign: 'center' },
  tdRight: { textAlign: 'right' },

  orderQtyCell: {
    flex: 1, alignItems: 'center',
  },
  orderQtyText: {
    fontSize: FontSize.sm, fontWeight: '700', color: Colors.danger,
    backgroundColor: Colors.dangerBg, borderRadius: Radius.sm,
    paddingHorizontal: 8, paddingVertical: 2, overflow: 'hidden',
    textAlign: 'center',
  },

  totalRow: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: Spacing.lg, paddingVertical: Spacing.md,
    backgroundColor: Colors.bgSecondary, borderTopWidth: 1, borderTopColor: Colors.borderMedium,
  },
  totalLabel: { flex: 1, fontSize: FontSize.sm, fontWeight: '600', color: Colors.textSecondary },
  totalValue: { flex: 1, fontSize: FontSize.sm, fontWeight: '700', color: Colors.textPrimary },

  // Empty states
  emptyDetail: { alignItems: 'center', padding: Spacing.xxxl, gap: Spacing.md },
  emptyTitle: { fontSize: FontSize.lg, fontWeight: '600', color: Colors.textPrimary },
  emptyText: { fontSize: FontSize.sm, color: Colors.textTertiary, textAlign: 'center', lineHeight: 20 },

  // Footer
  detailFooter: {
    padding: Spacing.lg, borderTopWidth: 0.5, borderTopColor: Colors.borderLight,
    backgroundColor: Colors.bgPrimary,
  },
  markSubmittedBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm,
    backgroundColor: Colors.success, borderRadius: Radius.lg,
    paddingVertical: Spacing.md + 2,
  },
  markSubmittedText: { color: Colors.bgPrimary, fontSize: FontSize.base, fontWeight: '700' },
  submittedFooter: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.sm,
    backgroundColor: Colors.successBg, borderRadius: Radius.lg,
    paddingVertical: Spacing.md + 2,
  },
  submittedFooterText: { fontSize: FontSize.sm, color: Colors.success, fontWeight: '500' },

  // ── Edit Modal ──
  editModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: Spacing.lg, borderBottomWidth: 0.5, borderBottomColor: Colors.borderLight },
  editModalTitle: { fontSize: FontSize.lg, fontWeight: '600', color: Colors.textPrimary },
  editModalCancel: { fontSize: FontSize.base, color: Colors.info },
  editModalBody: { padding: Spacing.lg },

  // Vendor edit row
  vendorEditRow: { flexDirection: 'row', gap: Spacing.sm, marginBottom: Spacing.lg, borderBottomWidth: 0.5, borderBottomColor: Colors.borderLight, paddingBottom: Spacing.lg },
  vendorEditFields: { flex: 1 },
  formField: { marginBottom: Spacing.sm },
  formLabel: { fontSize: FontSize.xs, color: Colors.textSecondary, marginBottom: 4 },
  formInput: { borderWidth: 0.5, borderColor: Colors.borderMedium, borderRadius: Radius.md, padding: Spacing.md, fontSize: FontSize.base, color: Colors.textPrimary, backgroundColor: Colors.bgSecondary },
  chipRow: { flexDirection: 'row', gap: 4 },
  chip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: Radius.round, backgroundColor: Colors.bgSecondary, borderWidth: 0.5, borderColor: Colors.borderLight },
  chipActive: { backgroundColor: Colors.textPrimary, borderColor: Colors.textPrimary },
  chipText: { fontSize: FontSize.xs, color: Colors.textSecondary },
  chipTextActive: { color: Colors.bgPrimary, fontWeight: '500' },
  removeBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.dangerBg, alignItems: 'center', justifyContent: 'center', alignSelf: 'center' },

  addRowBtn: { borderWidth: 1, borderColor: Colors.borderLight, borderStyle: 'dashed', borderRadius: Radius.md, padding: Spacing.md, alignItems: 'center', marginBottom: Spacing.lg },
  addRowBtnText: { fontSize: FontSize.sm, color: Colors.info, fontWeight: '500' },
  saveBtn: { backgroundColor: Colors.textPrimary, borderRadius: Radius.md, padding: Spacing.md + 2, alignItems: 'center' },
  saveBtnText: { color: Colors.bgPrimary, fontSize: FontSize.base, fontWeight: '600' },
});
